// profile
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE'

export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE'

//bill calculate
export const CHANGE_PERSON_NUMBER      = 'CHANGE_PERSON_NUMBER'
export const ADD_PROMOTION_CODE        = 'ADD_PROMOTION_CODE'
export const REMOVE_ALL_PROMOTION_CODE = 'REMOVE_ALL_PROMOTION_CODE'

//promotion list
export const GET_PROMOTION_ENABLE_LIST_REQUEST = 'GET_PROMOTION_ENABLE_LIST_REQUEST'
export const GET_PROMOTION_ENABLE_LIST_SUCCESS = 'GET_PROMOTION_ENABLE_LIST_SUCCESS'
export const GET_PROMOTION_ENABLE_LIST_FAILURE = 'GET_PROMOTION_ENABLE_LIST_FAILURE'