// profile
export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST"
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE"

export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST"
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS"
export const EDIT_PROFILE_FAILURE = "EDIT_PROFILE_FAILURE"

//bill calculate
export const CHANGE_PERSON_NUMBER      = "CHANGE_PERSON_NUMBER"
export const ADD_PROMOTION_CODE        = "ADD_PROMOTION_CODE"
export const ADD_PROMOTION_CODE_LIST   = "ADD_PROMOTION_CODE_LIST"
export const REMOVE_ALL_PROMOTION_CODE = "REMOVE_ALL_PROMOTION_CODE"
export const REMOVE_PROMOTION_BY_ORDER = "REMOVE_PROMOTION_BY_ORDER"

//promotion
export const GET_PROMOTION_ENABLE_LIST_REQUEST = "GET_PROMOTION_ENABLE_LIST_REQUEST"
export const GET_PROMOTION_ENABLE_LIST_SUCCESS = "GET_PROMOTION_ENABLE_LIST_SUCCESS"
export const GET_PROMOTION_ENABLE_LIST_FAILURE = "GET_PROMOTION_ENABLE_LIST_FAILURE"

export const GET_PROMOTION_LIST_REQUEST = "GET_PROMOTION_LIST_REQUEST"
export const GET_PROMOTION_LIST_SUCCESS = "GET_PROMOTION_LIST_SUCCESS"
export const GET_PROMOTION_LIST_FAILURE = "GET_PROMOTION_LIST_FAILURE"

export const GET_PROMOTION_ONE_REQUEST = "GET_PROMOTION_ONE_REQUEST"
export const GET_PROMOTION_ONE_SUCCESS = "GET_PROMOTION_ONE_SUCCESS"
export const GET_PROMOTION_ONE_FAILURE = "GET_PROMOTION_ONE_FAILURE"

export const UPDATE_PROMOTION_REQUEST = "UPDATE_PROMOTION_REQUEST"
export const UPDATE_PROMOTION_SUCCESS = "UPDATE_PROMOTION_SUCCESS"
export const UPDATE_PROMOTION_FAILURE = "UPDATE_PROMOTION_FAILURE"

export const CREATE_PROMOTION_REQUEST = "CREATE_PROMOTION_REQUEST"
export const CREATE_PROMOTION_SUCCESS = "CREATE_PROMOTION_SUCCESS"
export const CREATE_PROMOTION_FAILURE = "CREATE_PROMOTION_FAILURE"

//bill
export const GET_ONE_BILL_REQUEST = "GET_ONE_BILL_REQUEST"
export const GET_ONE_BILL_SUCCESS = "GET_ONE_BILL_SUCCESS"
export const GET_ONE_BILL_FAILURE = "GET_ONE_BILL_FAILURE"

export const ADD_BILL_REQUEST     = "ADD_BILL_REQUEST"
export const ADD_BILL_SUCCESS     = "ADD_BILL_SUCCESS"
export const ADD_BILL_FAILURE     = "ADD_BILL_FAILURE"

//reserve